### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by bedletskyi** [bedletskyi/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by rasamashka** [comment]
EXPERIENCE
NOW

March 26, 2018 - today
Marketing analyst at KT Ukraine.
•	I collect and analyze the prices of the company's products on the Internet market of Ukraine.
•	Maintain product prices on the Internet market in accordance with the company's pricing policy.

BACK THEN
November 29, 2018 – November 6, 2019
Join the army. – My watch has begun… ©Jon Snow
•	Was engaged in professional cleaning of the territory:
o	Waving a broom on the parade ground
o	The master collection of cigarette butts on the territory 
o	Branded floor washing with co-workers shampoo
•	I held a machine gun in my hands.

October 22, 2017 - March 23, 2018
Electrical engineer KP " Zhilmassiv» 

June 11, 2017 – November 1, 2017
Full Stack PHP Developer - Freelance (UpWork.com) 
•	Worked on development using the LAMP stack.
•	Integrated Oauth2 authentication, Google Maps API, and GetRespose API.
•	Made up sites and screwed the layout to WordPress, as well as fixed bugs on existing websites.

WAY BACK THEN
2016
Renamed the contact of the girl to Anastasia Salamakha more affectionate. – I didn't do it because she told me to. P.S. I hope she doesn't see it) 

June 26, 2016 – August 15, 2016
Specialist in repair and maintenance of electrical installations in Magnit LLC
•	Repair and maintenance of electric motors and transformer substations.

July 28, 2014
First time abroad (Language practice in France) 

September 1, 2012 
Joined TSATU

October 15, 1995
Born in the village. Billmac, Ukraine.
